---
name: HACS/Hassfest validation

"on":
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
      - uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration
          ignore: brands,repository,topics

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
